export {default as Navbar} from "./navbar/Navbar"
export {default as Slider} from "./slider/Slider"
export {default as ShowCard} from "./showCard/ShowCard"
export {default as LoginForm} from "./loginForm/LoginForm"
export {default as SignUpForm} from "./Register/SignUpForm"
export {default as Detail} from "./Detail/Detail"